# Generated by Django 4.0.4 on 2023-06-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.TextField(default=''),
        ),
    ]
